server:
  port: 7878
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7878/eureka
  server:
    enable-self-preservation: false # 测试时关闭自我保护机制，保证不可用服务及时踢出